name: Android build
on:
  workflow_call:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
          link-to-sdk: true

      - name: Compile (arm32)
        run: scons platform=android arch=arm32 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Compile (arm64)
        run: scons platform=android arch=arm64 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Compile (x86_32)
        run: scons platform=android arch=x86_32 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Compile (x86_64)
        run: scons platform=android arch=x86_64 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-android
          path: ./pixelpart-plugin/addons/pixelpart/bin
