name: iOS build
on:
  workflow_call:

jobs:
  build-ios:
    runs-on: macOS-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Compile
        run: python build.py platform=ios

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-ios
          path: ./pixelpart-plugin/addons/pixelpart/bin
