name: Linux arm build
on:
  workflow_call:

jobs:
  build-linux-arm:
    runs-on: ubuntu-22.04-arm
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install common dependencies
        uses: ./.github/actions/deps
        with:
          python-arch: arm64

      - name: Compile (arm64)
        run: scons platform=linux arch=arm64 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-linux-arm
          path: ./pixelpart-plugin/addons/pixelpart/bin
