name: Linux build
on:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Install gcc-multilib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib
          sudo apt-get install g++-multilib

      - name: Compile (x86_64)
        run: scons platform=linux arch=x86_64 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Compile (x86_32)
        run: scons platform=linux arch=x86_32 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-linux
          path: ./pixelpart-plugin/addons/pixelpart/bin
