name: Windows build
on:
  workflow_call:

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install common dependencies
        uses: ./.github/actions/deps

      - name: Compile (x86_64)
        run: scons platform=windows arch=x86_64 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Compile (x86_32)
        run: scons platform=windows arch=x86_32 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Compile (arm64)
        run: scons platform=windows arch=arm64 target=template_release generate_bindings=true disable_exceptions=false -j 4

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pixelpart-windows
          path: ./pixelpart-plugin/addons/pixelpart/bin
